### ISSUE TITLE
[Bug] TypeError: initialize() got an unexpected keyword argument 'job_name'

### ISSUE THREAD

**Issue by turian** [facebookresearch/hydra#829]
# 🐛 Bug

The [compose API doc](https://hydra.cc/docs/next/experimental/compose_api) specifies that you use parameter job_name to initialize, but this causes an error.

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
from hydra.experimental import compose, initialize

# global initialization
initialize(config_path="conf", job_name="test_app")
```

This is from the [compose API doc](https://hydra.cc/docs/next/experimental/compose_api) 

** Stack trace/error message **
```
TypeError: initialize() got an unexpected keyword argument 'job_name'
```

## Expected Behavior

Code from the API doc should run without error.

## System information
- **Hydra Version** :  1.0.0rc1
- **Python version** : 3.7.7
- **Virtual environment type and version** : n/a
- **Operating system** : OSX

## Additional context

n/a

**Comment by jieru-hu** [comment]
This should work in hydra-core 1.0.0rc2. could you pls upgrade and try again?

```
pip install hydra-core --upgrade --pre
```

**Comment by omry** [comment]
This is covered by tests and should work with the right version of Hydra. reopen if you still have issues after you upgrade.

**Comment by veritas9872** [comment]
@omry I currently have version 1.1.1 and the same issue occurs.

**Comment by veritas9872** [comment]
Found that it was an issue of default settings. I fixed it by using _recursive_: False but I have no idea why this worked.

**Comment by Jasha10** [comment]
@veritas9872 feel free to open a new issue with a minimal reproducible example of the bug that you are seeing.
